site_name: Education-Centre
site_url: "https://github.com/EliVolsch/Education-Centre"
docs_dir: ./docs/src
site_dir: ./docs/site
repo_name: "Learn-Centre"
repo_url: "https://github.com/EliVolsch/Education-Centre"
edit_uri: "https://github.com/EliVolsch/Education-Centre/blob/main/docs/"
theme:
  name: material
  direction: ltr
  include_search_page: true
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
copyright: Kartoza and Contributors

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
        - attr_list
        - pymdownx.highlight:
                  anchor_linenums: true
        - pymdownx.inlinehilite
        #- mdx_truly_sane_lists
        - toc:
                  permalink: true
                   #slugify: !!python/name:pymdownx.slugs.slugify
        - pymdownx.snippets:
                  base_path: .
        - admonition
        - tables
        - pymdownx.details
        - pymdownx.caret
        - pymdownx.keys
        - pymdownx.mark
        - pymdownx.tilde
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.emoji:
                  emoji_generator: !!python/name:materialx.emoji.to_svg
                  emoji_index: !!python/name:materialx.emoji.twemoji

nav:
  - Home:
      - /index.md # short intro on project here
  - Learning Materials:
      - /explore.md # this will be menu file with all courses
      - Figma: /figma/index.md
      - Mkdocs Materials: /mkdocs/index.md
  - Contribute:
      - index.md #Why should people contribute to this platform? Link contributors gh handles
      - How to contribute: contribute.md
      - Contribution Guidelines: guidelines.md
  - About:
      - /index.md
      - Terms of use: about/terms.md
      - License: about/license.md
  - Help: help.md